#!/usr/bin/env bash

docker run --rm  -v "$(realpath $(pwd))":/app "$(docker build -q -f=docker/qa.dockerfile docker)" /bin/bash -c \
  "php /composer/vendor/bin/phpcs --standard=psr2 src \
&& php /composer/vendor/bin/phpunit --testsuite=unit\
&& php /composer/vendor/bin/phpmd src text phpmd.xml\
&& php /composer/vendor/bin/phpcpd src\
&& php /composer/vendor/bin/phpmnd src --non-zero-exit-on-violation\
&& php /composer/vendor/bin/phpcdm src --non-zero-exit-on-violation\
&& php /composer/vendor/bin/phpdoccheck -d src\
&& php /composer/vendor/bin/phpcs --standard=psr2 src\
&& php /composer/vendor/bin/phpstan analyze src --level=1"
if [ $? != 0 ]; then
  echo "Fix errors before commit."
  echo "Try run \
  docker run --rm -it -v \"\$(realpath \$(pwd))\":/app \"\$(docker build -q -f=qa.dockerfile docker)\" \
  php /composer/vendor/bin/phpcbf --standard=psr2 src"
  exit 1
fi


for file in ./examples/*.php
do
	if [[ -f ${file} ]]; then
		php ${file}
		if [ $? != 0 ]
		then
			echo "Example broken: "
			echo ${file}
			exit 1
		fi
	fi
done
